services:
  - type: web
    name: air-monitor
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: air-monitor-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
databases:
  - name: air-monitor-db
    plan: free
