services:
  - type: web
    name: air-quality-monitoring-backend
    env: node
    plan: free
    buildCommand: "npm install && node db/init.js"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
    disk:
      - name: air-quality-disk
        mountPath: /var/data
