services:
  - type: web
    name: esp32-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase: esp32-db
      - key: SECRET_KEY
        value: "my-super-secret-key" # แก้ไขเป็น SECRET_KEY ที่คุณต้องการ
databases:
  - name: esp32-db
    plan: free
    region: oregon
